python motrun.py \
     --epochs=10000  \
     --batch-size=4 \
     --K=5 \
     --c-dim=512 \
     --n-hidden-statistic=1  \
     --hidden-dim-statistic=2000  \
     --n-stochastic=1 \
     --z-dim=16 \
     --n-hidden=1 \
     --hidden-dim=2000  \
     --viz-interval=2000 \
     --save_interval=2000 \
     --clip-gradients=True \
     --data-dir=/mnt/ClearWaterBay/Deep_SORT_data/MOT16_for_NeuralStat  \
     --output-dir=output/ \
